# Generated by Django 3.1 on 2021-02-01 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_auto_20210116_2216'),
        ('miscellaneous', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_Most_Popular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, null=True)),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.blog')),
            ],
        ),
    ]
