# Generated by Django 3.1 on 2021-02-22 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_auto_20210116_2216'),
        ('miscellaneous', '0004_home_intro_1_home_intro_2_home_intro_3_home_intro_4_home_intro_5'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boss_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.blog')),
            ],
        ),
    ]
