# Generated by Django 3.1 on 2021-01-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_section',
            old_name='section_identifier',
            new_name='section_slug',
        ),
        migrations.AlterField(
            model_name='blog_section',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
