# Generated by Django 3.1 on 2021-01-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_auto_20210114_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_section',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='blog_section'),
        ),
        migrations.AddField(
            model_name='blog_section',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='blog_section'),
        ),
    ]
