# Generated by Django 3.1 on 2021-01-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_auto_20210115_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='main_image',
            new_name='image_1',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='comment_count',
        ),
        migrations.AlterField(
            model_name='blog',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='special_blog',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
