# Generated by Django 3.1 on 2021-01-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_auto_20210115_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image_credit',
            field=models.TextField(blank=True, null=True),
        ),
    ]
