# Generated by Django 3.1 on 2021-01-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_blog_image_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='read_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
