# Generated by Django 3.1 on 2021-01-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_auto_20210115_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_section',
            name='index',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
