# Generated by Django 3.1 on 2021-02-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
