# Generated by Django 3.1 on 2021-02-22 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0010_instagram_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.TextField(blank=True, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='author')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='author')),
            ],
        ),
        migrations.CreateModel(
            name='Author_SM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sm_name', models.CharField(blank=True, max_length=150, null=True)),
                ('sm_icon', models.CharField(blank=True, max_length=150, null=True)),
                ('sm_url', models.TextField(blank=True, null=True)),
                ('fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.author')),
            ],
        ),
    ]
